apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "postgrest-tandem.fullname" . }}-postgres
  labels:
    app: {{ include "postgrest-tandem.fullname" . }}
    component: postgres
spec:
  serviceName: {{ include "postgrest-tandem.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "postgrest-tandem.fullname" . }}
      component: postgres
  template:
    metadata:
      labels:
        app: {{ include "postgrest-tandem.fullname" . }}
        component: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - secretRef:
                name: {{ include "postgrest-tandem.fullname" . }}-postgres
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U {{ .Values.postgres.username }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U {{ .Values.postgres.username }}
            initialDelaySeconds: 5
            periodSeconds: 5
          {{- if .Values.postgres.resources }}
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      securityContext:
        fsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "postgrest-tandem.fullname" . }}-postgres
