apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "name" . }}-postgrest
  labels:
    app: {{ include "name" . }}
type: Opaque
stringData:
  PGRST_DB_URI: {{ printf "postgres://%s:%s@%s-postgres:%d/%s" .Values.postgres.username .Values.postgres.password (include "name" .) (.Values.postgres.port | int) .Values.postgres.database | quote }}
  PGRST_DB_SCHEMAS: {{ .Values.postgrest.schemas | quote }}