apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "name" . }}-postgres
  labels:
    app: {{ include "name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize }}
