apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "postgrest-tandem.fullname" . }}-postgres
  labels:
    app: {{ include "postgrest-tandem.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.postgres.storageClass }}
  storageClassName: {{ .Values.postgres.storageClass | quote }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize }}
