apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "name" . }}-postgres
  labels:
    app: {{ include "name" . }}
    component: postgres
spec:
  clusterIP: None
  selector:
    app: {{ include "name" . }}
    component: postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: 5432
      name: postgres
