apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "postgrest-tandem.fullname" . }}-postgrest
  labels:
    app: {{ include "postgrest-tandem.fullname" . }}
    component: postgrest
spec:
  type: ClusterIP
  selector:
    app: {{ include "postgrest-tandem.fullname" . }}
    component: postgrest
  ports:
    - port: {{ .Values.postgrest.port }}
      targetPort: {{ .Values.postgrest.port }}
      name: http
