apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "postgrest-tandem.fullname" . }}-postgrest
  labels:
    app: {{ include "postgrest-tandem.fullname" . }}
type: Opaque
stringData:
  PGRST_DB_URI: {{ printf "postgresql://authenticator:%s@%s-postgres:%d/%s" .Values.postgres.authenticatorPassword (include "postgrest-tandem.fullname" .) (.Values.postgres.port | int) .Values.postgres.database | quote }}
  PGRST_DB_SCHEMAS: {{ .Values.postgrest.schemas | quote }}
